name: Compile the project

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'File version (e.g. 1.1.0.0)'
        required: true
      tagname:
        description: 'Tag name (e.g. 1.1.0.0-test)'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          repository: SET19724/ESET-KeyGen-test
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Debug Directory Structure
        shell: bash
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Looking for Python files:"
          find . -name "*.py" -o -name "requirements.txt" | head -10
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Compile
        shell: bash
        run: |
          # Sprawdź czy jesteśmy w głównym katalogu repozytorium
          if [[ ! -f "main.py" ]] && [[ -d "ESET-KeyGen" ]]; then
            cd ESET-KeyGen
            echo "Moved to ESET-KeyGen directory"
          fi
          
          # Sprawdź czy main.py istnieje
          if [[ ! -f "main.py" ]]; then
            echo "Error: main.py not found in current directory: $(pwd)"
            find .. -name "main.py" | head -5
            exit 1
          fi
          
          python -m pip install --upgrade pip
          python -m pip install charset_normalizer pyinstaller -r requirements.txt
          pyinstaller --onefile --clean main.py
          chmod a+x ./dist/main
          
          # Utwórz katalog dla artefaktów
          mkdir -p ../release
          mv ./dist/main "../release/ESET-KeyGen_v${{ github.event.inputs.version }}_macos"

  
