name: Compile the project

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'File version (e.g. 1.1.0.0)'
        required: true
      tagname:
        description: 'Tag name (e.g. 1.1.0.0-test)'
        required: true
      release_name:
        description: 'Release name'
        required: true

jobs:
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: SET19724/ESET-KeyGen-test
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        
      - name: Compile macOS
        run: |
          if [[ ! -f "main.py" ]] && [[ -d "ESET-KeyGen" ]]; then
            cd ESET-KeyGen
          fi
          python -m pip install --upgrade pip
          pip install pyinstaller charset_normalizer -r requirements.txt
          pyinstaller --onefile --clean main.py
          chmod +x ./dist/main
          mkdir -p release
          mv ./dist/main "release/ESET-KeyGen_v${{ github.event.inputs.version }}_macos"

      - uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: release/ESET-KeyGen_v${{ github.event.inputs.version }}_macos

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: SET19724/ESET-KeyGen-test
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Compile Windows
        shell: pwsh
        run: |
          if (!(Test-Path "main.py") -and (Test-Path "ESET-KeyGen")) {
            Set-Location "ESET-KeyGen"
          }
          pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
          pyinstaller --onefile --clean main.py
          New-Item -Type Directory -Force -Path ".\release" | Out-Null
          Copy-Item ".\dist\main.exe" ".\release\ESET-KeyGen_v${{ github.event.inputs.version }}_win64.exe"
          Copy-Item ".\dist\main.exe" ".\release\ESET-KeyGen_v${{ github.event.inputs.version }}_win32.exe"

      - uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: release/ESET-KeyGen_v${{ github.event.inputs.version }}_*.exe

  release:
    needs: [macOS, windows]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: macos-artifact
        continue-on-error: true

      - uses: actions/download-artifact@v4
        with:
          name: windows-artifacts
        continue-on-error: true

      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.release_name }}
          tag_name: v${{ github.event.inputs.tagname }}
          draft: false
          generate_release_notes: true
          files: ESET-KeyGen_v${{ github.event.inputs.version }}_*
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
